rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - rbx-2
  - jruby-19mode
  - jruby-head

script: "bundle exec rspec"

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_3.1.gemfile
